const Products = [
    {
        id: 0,
        name: "Cozy White Mug",
        price: 7.99,
        instock: 100,
        description: "Experience the ultimate in comfort and style with the Cozy White Mug! This beautifully designed mug embodies simplicity and elegance, making it a perfect addition to any kitchen or office",
        imgSrc: "https://media.istockphoto.com/id/1414016924/photo/white-mockup-mug-with-copy-space-and-houseplant-at-the-background.jpg?s=612x612&w=0&k=20&c=2CCGUMWlr3yJrHGtYAo1ZDPChVfoWRZtAmD9qhwjPko=",
    },
    {
        id: 1,
        name: "Crimson Red Mug",
        price: 4.99,
        instock: 100,
        description: "Ignite your passion for great coffee and tea with the Crimson Red Mug! This vibrant mug is more than just a drinkware piece—it's a bold statement. Hurry and dont miss out on this oportunity!",
        imgSrc: "https://media.istockphoto.com/id/171368204/photo/red-cup.jpg?s=612x612&w=0&k=20&c=q0CQtZJAGs8VXm2B7462QDJ0tlk18h1EPApvvZNgBus=",
    },
    {
        id: 2,
        name: "Verdant Green Mug",
        price: 6.99,
        instock: 100,
        description: "Brighten your day with the Verdant Green Mug, a perfect blend of nature-inspired charm and functionality. This beautifully crafted mug showcases a rich green hue",
        imgSrc: "https://media.istockphoto.com/id/869295342/photo/image-of-coffee-cup-isolated-with-clipping-path.jpg?s=612x612&w=0&k=20&c=AWQmOCfkjecoezwGk-jFSWKEO6xRzBnM_Jkj5LcD0o~",
    },
    {
        id: 3,
        name: "Cream Elegance Mug",
        price: 10.99,
        instock: 100,
        description: "Introducing the Cream Elegance Mug, a timeless piece that embodies sophistication and warmth. This beautifully crafted mug features a soft cream color that complements any decor.",
        imgSrc: "https://img.freepik.com/premium-photo/color-burst-chaos-coffee-mug-mockup-brand-merchandise_901408-7480.jpg",
    },
    {
        id: 4,
        name: "Blush Pink Mug",
        price: 5.99,
        instock: 100,
        description: "Elevate your sipping experience with the charming Blush Pink Mug! This delightful mug is a perfect blend of style and functionality, designed to bring a touch of elegance to your daily routine",
        imgSrc: "https://media.istockphoto.com/id/617374430/photo/pink-ceramic-cup-isolated-on-white-background.jpg?s=612x612&w=0&k=20&c=TBBMp_4y1_K10vTn2Uv81RjA7I43sZv4Z3pxtb9Xq0A=",
    },
    {
        id: 5,
        name: "Sunset Orange Mug",
        price: 7.99,
        instock: 100,
        description: "Brighten up your day with the Sunset Orange Mug! This vibrant mug is designed to add a pop of color to your morning routine or afternoon break. Hurry and dont miss this oportunity.",
        imgSrc: "https://media.istockphoto.com/id/1146776554/fr/photo/gros-plan-de-tasse-%C3%A0-vapeur-de-caf%C3%A9-sur-comptoir-de-cuisine-en-d%C3%A9but-de-matin%C3%A9e.jpg?s=612x612&w=0&k=20&c=MwezknFHCfrKL2i8KEv8WZGU8KqSVSmJp9UwrMT3yIs=",
    },
    {
        id: 6,
        name: "Cozy Sip Mug",
        price: 11.99,
        instock: 100,
        description: "Introducing the Cozy Sip Mug, designed with your comfort in mind. This mug combines style and functionality to create the ultimate sipping experience.",
        imgSrc: "https://img.freepik.com/premium-photo/white-coffee-mug-wooden-table-with-words-o-side_1058796-39492.jpg",
    },
    {
        id: 7,
        name: "Kiyomi Mug",
        price: 15.99,
        instock: 100,
        description: "Introducing the Kiyomi Mug, a tribute to the elegance and tradition of Japanese craftsmanship. Inspired by timeless Japanese design.",
        imgSrc: "https://www.shutterstock.com/image-photo/yellow-ceramic-mug-isolated-on-600nw-2224244583.jpg",
    },
    {
        id: 8,
        name: "Luxe Mug",
        price: 10.99,
        instock: 100,
        description: "Introducing the Luxe Mug, where elegance meets everyday indulgence. Crafted with precision, this mug is more than just a vessel—it's a statement..",
        imgSrc: "https://parkstreetbooks.com/cdn/shop/files/C40004_20_02_G_001_829x828_jpg_829x.webp?v=1701032167",
    },

];
